import { size, variants } from "./config.model";

export const variantStyle: { [ key in variants ]: { [ key: string ]: string | boolean | number } } = {
    'outline': {
        cursor: 'cursor-pointer',
        disabled: false,
        display: 'inline-flex',
        color: 'bg-neutral-50',
        text: 'text-neutral-950',
        hover: "hover:bg-neutral-300",
        disabled_color: "disabled:bg-neutral-300",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        border: "solid",
        border_width: "border-\[1px\]",
        border_color: "border-neutral-950",
        gap: "gap-2",
    },
    'primary': {
        cursor: 'cursor-pointer',
        disabled: false,
        display: 'inline-flex',
        color: 'bg-blue-600',
        text: "text-neutral-50",
        hover: "hover:bg-blue-500",
        disabled_color: "disabled:bg-blue-500",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        gap: "gap-2",
    },
    'secondary': {
        cursor: 'cursor-pointer',
        disabled: false,
        display: 'inline-flex',
        color: "bg-zinc-400",
        text: "text-neutral-950",
        hover: "hover:bg-zinc-300",
        disabled_color: "disabled:bg-zinc-300",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        gap: "gap-2",
    },
    'tertiary': {
        cursor: 'cursor-pointer',
        disabled: false,
        display: 'inline-flex',
        color: "bg-fuchsia-600",
        text: "text-neutral-50",
        hover: "hover:bg-fuchsia-500",
        disabled_color: "disabled:bg-fuchsia-500",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        gap: "gap-2",
    },
    'danger': {
        cursor: 'cursor-pointer',
        disabled: false,
        display: 'inline-flex',
        color: "bg-red-600",
        text: "text-neutral-50",
        hover: "hover:bg-red-400",
        disabled_color: "disabled:bg-red-400",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        gap: "gap-2",
    },
    'success': {
        cursor: 'cursor-pointer',
        disabled: false,
        display: 'inline-flex',
        color: "bg-emerald-600",
        text: "text-neutral-50",
        hover: "hover:bg-emerald-400",
        disabled_color: "disabled:bg-emerald-400",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        gap: "gap-2",
    },
    'none': {
        cursor: "cursor-pointer",
        disabled: false,
        display: 'inline-flex',
        color: 'bg-neutral-50',
        text: 'text-neutral-950',
        hover: 'hover:bg-neutral-50',
        disabled_color: "disabled:bg-neutral-300",
        disabled_opacity: "disabled:opacity-50",
        position: 'items-center',
        align: 'justify-content',
        x_padding: 'px-4',
        y_padding: 'py-2',
        border_radius: 'rounded-md',
        wrap: 'whitespace-nowrap',
        gap: "gap-2",
    }
}

export const sizeStyle: { [ key in size ]: { [ key: string ]: string } } = {
    'xs': {
        weight: 'font-normal',
        text_size: 'text-xs',
        height: 'h-8',
        width: 'min-w-20',
    },
    's': {
        weight: 'font-normal',
        text_size: 'text-sm',
        height: 'h-9',
        width: 'min-w-24',
    },
    'm': {
        weight: 'font-medium',
        text_size: 'text-base',
        height: 'h-10',
        width: 'min-w-28',
    },
    'l': {
        weight: 'font-medium',
        text_size: 'text-lg',
        height: 'h-11',
        width: 'min-w-32',
    },
    'xl': {
        weight: 'font-medium',
        text_size: 'text-xl',
        height: 'h-12',
        width: 'min-w-40',
    }
}